# Generated by Django 5.1.1 on 2026-09-16 06:21

import applications.attachments
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0011_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariza_raqami', models.CharField(max_length=32, unique=True, verbose_name='Ariza raqami')),
                ('buyurtma_nomi', models.CharField(max_length=255, verbose_name='Buyurtma nomi')),
                ('buyurtma_soni', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Buyurtma soni')),
                ('olchov_birligi', models.CharField(help_text='ta, kg, m and so on. Free text: REQ-ARIZA-003 gives examples and no page maintains a list of units.', max_length=16, verbose_name='O`lchov birligi')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('pdf', models.FileField(blank=True, help_text='PDF, eng ko`pi bilan 10 MB (DEC-019).', storage=applications.attachments.attachment_storage, upload_to='arizalar/%Y/%m', validators=[applications.attachments.validate_pdf], verbose_name='Ariza (PDF)')),
                ('kelib_tushgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Kelib tushgan sana')),
                ('stage', models.CharField(choices=[('incoming', 'Kelib tushgan'), ('accepted', 'Qabul qilingan'), ('rejected', 'Inkor etilgan')], default='incoming', max_length=16)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='reference.department', verbose_name='Bo`lim nomi')),
                ('mahsulot_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='reference.mahsulotturi', verbose_name='Mahsulot Turi')),
                ('sender', models.ForeignKey(blank=True, help_text='Who TASK-UZK-023 and TASK-UZK-024 notify. Nullable because the DEC-016 approval chain that would identify them is not built.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_applications', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ('-kelib_tushgan_sana', '-id'),
            },
        ),
    ]
