# Generated by Django 5.1.1 on 2026-09-16 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('reference', '0013_code_the_seeded_ariza_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_applications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan'),
        ),
        migrations.AddField(
            model_name='application',
            name='qabul_qilingan_sana',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan sana'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, help_text='What a person reads, beside the stage the workflow branches on. Nullable because DEC-017 lets an administrator delete every status, and a master data page must not be able to stop an application being accepted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='reference.arizastatus', verbose_name='Status'),
        ),
    ]
