# Generated by Django 5.1.1 on 2026-09-16 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_acceptance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='inkor_izohi',
            field=models.TextField(blank=True, help_text='Why it was rejected. REQ-ARIZA-005 makes this compulsory at the moment of rejection, which reject() enforces; the column is blank rather than null because an application that was never rejected has no comment, and that is an empty string.', verbose_name='Inkor izohi'),
        ),
        migrations.AddField(
            model_name='application',
            name='inkor_qilingan_sana',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inkor qilingan sana'),
        ),
        migrations.AddField(
            model_name='application',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_applications', to=settings.AUTH_USER_MODEL, verbose_name='Inkor qilgan'),
        ),
    ]
