# Generated by Django 5.1.1 on 2026-09-16 16:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_items'),
        ('reference', '0013_code_the_seeded_ariza_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationitem',
            name='buyurtma_soni',
            field=models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Buyurtma soni'),
        ),
        migrations.AddConstraint(
            model_name='applicationitem',
            constraint=models.CheckConstraint(condition=models.Q(('buyurtma_soni__gte', Decimal('0.001'))), name='order_line_quantity_is_positive', violation_error_message='Buyurtma soni noldan katta bo`lishi kerak.'),
        ),
    ]
