# Generated by Django 5.1.1 on 2026-09-16 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_order_quantity_floor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Who made the current assignment. Recorded here because DEC-024 wants every move in the log and TASK-UZK-052 builds the log: the record knows who and when, so the entry can be written when there is somewhere to write it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_assigned_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlagan'),
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The Katta Mutaxasis this application is for (REQ-ARIZA-007). Null until somebody is chosen, which is what an unassigned row on the Qabul qilingan page is.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlangan xodim'),
        ),
        migrations.AddField(
            model_name='application',
            name='tayinlangan_sana',
            field=models.DateTimeField(blank=True, help_text='When the current assignment was made. Re-assignment replaces it rather than keeping the first, because DEC-024 makes the assignment a fact about now and the history belongs in the section 10 log.', null=True, verbose_name='Tayinlangan sana'),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('incoming', 'Kelib tushgan'), ('accepted', 'Qabul qilingan'), ('assigned', 'Tayinlangan'), ('rejected', 'Inkor etilgan')], default='incoming', max_length=16),
        ),
    ]
