# Generated by Django 5.1.1 on 2026-09-16 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='xodim_qabul_qilgan_sana',
            field=models.DateTimeField(blank=True, help_text='When the assigned specialist took the work (REQ-ARIZA-013). A different fact from qabul_qilingan_sana, which is when the department accepted the application itself - one column meaning both would make the Qabul qilingan date unreadable. Cleared when the application moves to somebody else, because the next holder has not taken anything yet.', null=True, verbose_name='Xodim qabul qilgan sana'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('specialist_accepted', 'Xodim arizani qabul qildi')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When somebody was actually shown this. Null until then, and nothing sets it yet: TASK-UZK-054 is what delivers a notification, and this task only produces one.', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application', verbose_name='Ariza')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kimga')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
