# Generated by Django 5.1.1 on 2026-09-16 18:04

import applications.attachments
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_specialist_acceptance_and_notifications'),
        ('reference', '0013_code_the_seeded_ariza_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xarid_raqami', models.CharField(max_length=32, unique=True, verbose_name='Ariza raqami')),
                ('shartnoma_nomi', models.CharField(help_text='What the purchase is for (REQ-ARIZA-015).', max_length=255, verbose_name='Shartnoma nomi')),
                ('muddat_talabi', models.DateField(blank=True, help_text='When it is needed by (REQ-ARIZA-015).', null=True, verbose_name='Muddat talabi')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('pdf', models.FileField(blank=True, help_text='PDF, eng ko`pi bilan 10 MB (DEC-019).', storage=applications.attachments.attachment_storage, upload_to='arizalar/%Y/%m', validators=[applications.attachments.validate_pdf], verbose_name='Ariza (PDF)')),
                ('yaratilingan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('department', models.ForeignKey(help_text="Filled from the requester's own account (DEC-018), never typed.", on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications', to='reference.department', verbose_name='Bo`lim nomi')),
                ('status', models.ForeignKey(blank=True, help_text='Nullable for the reason Application.status is: DEC-017 lets an administrator delete every status, and a master data page must not be able to stop somebody raising a request.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications', to='reference.arizastatus', verbose_name='Xozirgi holati')),
            ],
            options={
                'verbose_name': 'Xarid arizasi',
                'verbose_name_plural': 'Xarid arizalari',
                'ordering': ('-yaratilingan_sana', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_nomi', models.CharField(max_length=255, verbose_name='Buyurtma nomi')),
                ('buyurtma_soni', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Buyurtma soni')),
                ('olchov_birligi', models.CharField(help_text='ta, kg, m and so on. Free text: REQ-ARIZA-003 gives examples and no page maintains a list of units.', max_length=16, verbose_name='O`lchov birligi')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applications.purchaseapplication', verbose_name='Xarid arizasi')),
                ('mahsulot_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_application_items', to='reference.mahsulotturi', verbose_name='Mahsulot Turi')),
            ],
            options={
                'verbose_name': 'Xarid arizasi qatori',
                'verbose_name_plural': 'Xarid arizasi qatorlari',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('buyurtma_soni__gte', Decimal('0.001'))), name='purchase_order_line_quantity_is_positive', violation_error_message='Buyurtma soni noldan katta bo`lishi kerak.')],
            },
        ),
    ]
