# Generated by Django 5.1.1 on 2026-09-16 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_purchase_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='purchase_application',
            field=models.ForeignKey(blank=True, help_text='The other kind of record a notification can be about. Exactly one of the two is set, which the constraint below says.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.purchaseapplication', verbose_name='Xarid arizasi'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='bolim_boshligi_sanasi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bo`lim boshlig`i tasdiqlagan sana'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='direktor_sanasi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Direktor tasdiqlagan sana'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='inkor_izohi',
            field=models.TextField(blank=True, help_text='Why it was refused. REQ-ARIZA-020 makes this the point of the action rather than a decoration on it: the requester is told why, so a rejection with no reason is not one reject() performs.', verbose_name='Inkor izohi'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='inkor_qilgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Inkor qilgan'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='inkor_sanasi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inkor qilingan sana'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='raised_application',
            field=models.OneToOneField(blank=True, help_text="The department's own application this request became when Direktor approved it (DEC-016). Null until then, and the only thing connecting a requester's record to the department's.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raised_from', to='applications.application', verbose_name='Yaratilgan ariza'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='stage',
            field=models.CharField(choices=[('awaiting_head', 'Bo`lim boshlig`i tasdig`ini kutmoqda'), ('awaiting_direktor', 'Direktor tasdig`ini kutmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Inkor etilgan')], default='awaiting_head', max_length=24),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='tasdiqlagan_bolim_boshligi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications_approved_as_head', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan bo`lim boshlig`i'),
        ),
        migrations.AddField(
            model_name='purchaseapplication',
            name='tasdiqlagan_direktor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications_approved_as_direktor', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan direktor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='applications.application', verbose_name='Ariza'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('specialist_accepted', 'Xodim arizani qabul qildi'), ('purchase_rejected', 'Xarid arizasi inkor etildi')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', False), ('purchase_application__isnull', True)), models.Q(('application__isnull', True), ('purchase_application__isnull', False)), _connector='OR'), name='notification_is_about_one_record', violation_error_message='A notification is about an application or a purchase application, not both and not neither.'),
        ),
    ]
