# Generated by Django 5.1.1 on 2026-09-16 19:05

import applications.attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_purchase_application_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseapplication',
            name='asl_pdf',
            field=models.FileField(blank=True, help_text='The attachment exactly as it was uploaded. Blank until an approval stamps pdf, and kept from then on: the stamp rewrites the document, and what a requester submitted should still be producible afterwards.', storage=applications.attachments.attachment_storage, upload_to='arizalar/asl/%Y/%m', verbose_name='Asl ilova (PDF)'),
        ),
    ]
