# Generated by Django 5.1.1 on 2026-09-16 19:26

import applications.attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_approval_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseapplication',
            name='asl_pdf',
            field=models.FileField(blank=True, help_text='The attachment exactly as it was uploaded. Blank until an approval stamps pdf, and from then on it names the original file where it already sits - it points at that file rather than storing a second copy of it, which is why upload_to matches the path the upload used. The #46 review found this declaring a directory nothing ever writes to.', storage=applications.attachments.attachment_storage, upload_to='arizalar/%Y/%m', verbose_name='Asl ilova (PDF)'),
        ),
    ]
