# Generated by Django 5.1.1 on 2026-09-16 19:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_original_attachment_path'),
        ('reference', '0013_code_the_seeded_ariza_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_raqami', models.CharField(max_length=32, unique=True, verbose_name='Shartnoma raqami')),
                ('qiymati', models.DecimalField(decimal_places=2, help_text='In UZS. Eighteen digits because a contract in soums runs to billions, and two decimal places because money has them. The floor is on the column for the reason the #33 review gave about order quantities: a rule on a form is a rule on one page.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Shartnoma qiymati')),
                ('stage', models.CharField(choices=[('agreed', 'Kelishinlingan'), ('sent', 'Tasdiqlashga yuborilgan'), ('signed', 'Tuzilgan'), ('rejected', 'Inkor etilgan')], default='agreed', max_length=16)),
                ('inkor_izohi', models.TextField(blank=True, help_text='Why it was refused, which REQ-SHARTNOMA-004 gives a column of its own. Empty until TASK-UZK-038 rejects one; the column is rendered from the start so that task has nowhere left to put it.', verbose_name='Izoh (Inkor etilgan)')),
                ('yaratilingan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('application', models.ForeignKey(help_text='The application this contract fulfils. PROTECT rather than CASCADE: a contract is an agreement with a supplier and deleting the request behind it should not take it with them.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='applications.application', verbose_name='Ariza')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim shartnoma qilgan')),
                ('shartnoma_turi', models.ForeignKey(blank=True, help_text='DEC-023 draws this from master data. Nullable because REQ-SHARTNOMA-004 does not list it as a column and the TASK-UZK-035 entry form is what asks for it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='reference.shartnomaturi', verbose_name='Shartnoma turi')),
                ('status', models.ForeignKey(blank=True, help_text='Nullable for the reason Application.status is: DEC-010 lets an administrator retire every status, and a master data page must not be able to stop a contract being recorded.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='reference.shartnomastatus', verbose_name='Holati')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='reference.supplier', verbose_name='Firma nomi')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
                'ordering': ('-yaratilingan_sana', '-id'),
            },
        ),
    ]
