# Generated by Django 5.1.1 on 2026-09-17 07:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='izoh',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='contract',
            name='muddat_talabi',
            field=models.DateField(blank=True, help_text='The deadline the customer set (REQ-SHARTNOMA-006). Optional, as it is on the purchase application: nothing says a contract must carry one.', null=True, verbose_name='Muddat talabi'),
        ),
        migrations.AddField(
            model_name='contract',
            name='shartnoma_sanasi',
            field=models.DateField(blank=True, help_text='The date on the contract itself, which REQ-SHARTNOMA-006 lists beside Yaratilingan sana. Two fields because they are two facts: when the agreement is dated, and when somebody typed it in. Nullable because every contract that existed before the entry form predates the question.', null=True, verbose_name='Shartnoma sanasi'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tolash_muddati',
            field=models.DateField(blank=True, help_text='When payment falls due (REQ-SHARTNOMA-006).', null=True, verbose_name='To`lash muddati'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='qiymati',
            field=models.DecimalField(decimal_places=2, help_text='In UZS (DEC-026). Eighteen digits because a contract in soums runs to billions, and two decimal places because money has them. Stored rather than summed on every read, because the lists and every later money report sort and total on it - and written by raise_contract() from the goods rows rather than supplied, because REQ-SHARTNOMA-006 makes it the total of everything.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Shartnoma qiymati'),
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_nomi', models.CharField(max_length=255, verbose_name='Buyurtma nomi')),
                ('buyurtma_soni', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Buyurtma soni')),
                ('olchov_birligi', models.CharField(help_text='ta, kg, m and so on. Free text: REQ-ARIZA-003 gives examples and no page maintains a list of units.', max_length=16, verbose_name='O`lchov birligi')),
                ('part_number', models.CharField(blank=True, help_text="The supplier's own code for this item. Free text and optional: REQ-SHARTNOMA-006 gives it a plain input, and not every firm catalogues what it sells.", max_length=64, verbose_name='Part Number')),
                ('narxi', models.DecimalField(decimal_places=2, help_text='The price of one, in UZS (DEC-026). The floor is on the column as well as on the form, which is what the review of #33 settled about order quantities: a rule on a form is a rule on one page.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Narxi')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applications.contract', verbose_name='Shartnoma')),
            ],
            options={
                'verbose_name': 'Shartnoma qatori',
                'verbose_name_plural': 'Shartnoma qatorlari',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('buyurtma_soni__gte', Decimal('0.001'))), name='contract_line_quantity_is_positive', violation_error_message='Miqdori noldan katta bo`lishi kerak.'), models.CheckConstraint(condition=models.Q(('narxi__gte', Decimal('0.01'))), name='contract_line_price_is_positive', violation_error_message='Narxi noldan katta bo`lishi kerak.')],
            },
        ),
    ]
