# Generated by Django 5.1.1 on 2026-09-17 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_contract_attachment'),
        ('reference', '0013_code_the_seeded_ariza_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='O`zgartirilgan sana')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Kim o`zgartirgan')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='applications.contract', verbose_name='Shartnoma')),
                ('from_status', models.ForeignKey(blank=True, help_text='Null for the first move. Contract.status is nullable because DEC-010 lets an administrator retire every status, so a contract can be entered with none - and the move away from nothing is the one most worth recording, not the one to refuse.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moves_away', to='reference.shartnomastatus', verbose_name='Oldingi holat')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves_here', to='reference.shartnomastatus', verbose_name='Yangi holat')),
            ],
            options={
                'verbose_name': 'Shartnoma holati o`zgarishi',
                'verbose_name_plural': 'Shartnoma holati o`zgarishlari',
                'ordering': ('-changed_at', '-id'),
            },
        ),
    ]
