# Generated by Django 5.1.1 on 2026-09-17 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_contract_status_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='yuborgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim yuborgan'),
        ),
        migrations.AddField(
            model_name='contract',
            name='yuborilgan_sana',
            field=models.DateTimeField(blank=True, help_text='When this contract was last sent for approval. Overwritten by a resend rather than kept per attempt: DEC-024 makes a resend the same act again, and the history of the attempts belongs in the section 10 log TASK-UZK-052 builds.', null=True, verbose_name='Tasdiqlashga yuborilgan sana'),
        ),
    ]
