# Generated by Django 5.1.1 on 2026-09-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_contract_sent_for_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='yuborishlar_soni',
            field=models.PositiveIntegerField(default=0, help_text='How many times this contract has gone for approval. The two columns above hold the last send and are overwritten by a resend, and the review of #60 pointed out that the log TASK-UZK-052 builds cannot recover what was never recorded - a contract rejected and resent three times before that task ships would show one send and no sign of the other two. How many times it came back is the question the department will actually ask, and a count answers it without building that log early.', verbose_name='Necha marta yuborilgan'),
        ),
    ]
