# Generated by Django 5.1.1 on 2026-09-17 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_contract_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tahrirlagan',
            field=models.ForeignKey(blank=True, help_text="Who last changed this contract's terms. Null until somebody does, which is most contracts. TASK-UZK-040 made editing an exclusive permission one person holds at a time, and the review of #64 pointed out that this was then the only mutation on a contract that did not record who made it - so if the permission changes hands twice in a week, nothing said which holder changed the price.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edited_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim tahrirlagan'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tahrirlangan_sana',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tahrirlangan sana'),
        ),
    ]
