# Generated by Django 5.1.1 on 2026-09-18 00:35

import django.core.validators
import django.db.models.deletion
import xarid.attachments
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Bo`lim Nomi')),
            ],
            options={
                'verbose_name': 'Bo`lim',
                'verbose_name_plural': 'Bo`limlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MahsulotTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_number', models.PositiveIntegerField(help_text='Six digits, the code the department knows the category by.', unique=True, verbose_name='Category Raqami')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Category Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Mahsulot Turi',
                'verbose_name_plural': 'Mahsulot Turlari',
                'ordering': ('category_number',),
            },
        ),
        migrations.CreateModel(
            name='ShartnomaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge_colour', models.CharField(choices=[('orange', 'orange'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('gray', 'gray')], default='orange', max_length=16, verbose_name='Badge Rangi')),
                ('position', models.PositiveIntegerField(blank=True, default=0, help_text="Ro'yhatdagi va hisobot ustunlaridagi tartib. Bo'sh qoldirilsa, oxiriga qo'shiladi.", verbose_name='Tartib')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Status Nomi')),
            ],
            options={
                'verbose_name': 'Shartnoma Status',
                'verbose_name_plural': 'Shartnoma Statuslari',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShartnomaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Shartnoma Turi')),
            ],
            options={
                'verbose_name': 'Shartnoma Turi',
                'verbose_name_plural': 'Shartnoma Turlari',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Specialty Nomi')),
            ],
            options={
                'verbose_name': 'User Specialty',
                'verbose_name_plural': 'User Specialties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='User Type')),
                ('badge_colour', models.CharField(choices=[('orange', 'orange'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('gray', 'gray')], default='orange', max_length=16, verbose_name='Badge Rangi')),
                ('is_system_role', models.BooleanField(default=False, help_text='One of the six DEC-013 fixes. The permission matrix names it, so it cannot be renamed or deleted from the User Types page.')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ArizaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge_colour', models.CharField(choices=[('orange', 'orange'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('gray', 'gray')], default='orange', max_length=16, verbose_name='Badge Rangi')),
                ('position', models.PositiveIntegerField(blank=True, default=0, help_text="Ro'yhatdagi va hisobot ustunlaridagi tartib. Bo'sh qoldirilsa, oxiriga qo'shiladi.", verbose_name='Tartib')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Status Nomi')),
                ('code', models.CharField(blank=True, choices=[('new', 'Yangi'), ('accepted', 'Qabul qilingan'), ('assigned', 'Tayinlangan'), ('cancelled', 'Bekor qilingan')], help_text='How the workflow finds this row. Set on the seeded statuses and empty on any an administrator adds.', max_length=16)),
            ],
            options={
                'verbose_name': 'Ariza Status',
                'verbose_name_plural': 'Ariza Statuslari',
                'ordering': ('position', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_ariza_status_code')],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ariza_raqami', models.CharField(max_length=32, unique=True, verbose_name='Ariza raqami')),
                ('buyurtmachi_ismi', models.CharField(blank=True, help_text='Who asked for this, as typed on the form (REQ-ARIZA-008).', max_length=255, verbose_name='Buyurtmachi ismi')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('pdf', models.FileField(blank=True, help_text='PDF, eng ko`pi bilan 10 MB (DEC-019).', storage=xarid.attachments.attachment_storage, upload_to='arizalar/%Y/%m', validators=[xarid.attachments.validate_pdf], verbose_name='Ariza (PDF)')),
                ('kelib_tushgan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Kelib tushgan sana')),
                ('qabul_qilingan_sana', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan sana')),
                ('inkor_izohi', models.TextField(blank=True, help_text='Why it was rejected; compulsory at the moment of rejection.', verbose_name='Inkor izohi')),
                ('inkor_qilingan_sana', models.DateTimeField(blank=True, null=True, verbose_name='Inkor qilingan sana')),
                ('xodim_qabul_qilgan_sana', models.DateTimeField(blank=True, help_text='When the assigned specialist took the work (REQ-ARIZA-013). Cleared when the application moves to somebody else.', null=True, verbose_name='Xodim qabul qilgan sana')),
                ('tayinlangan_sana', models.DateTimeField(blank=True, help_text='When the current assignment was made.', null=True, verbose_name='Tayinlangan sana')),
                ('stage', models.CharField(choices=[('incoming', 'Kelib tushgan'), ('accepted', 'Qabul qilingan'), ('assigned', 'Tayinlangan'), ('rejected', 'Inkor etilgan')], default='incoming', max_length=16)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_applications', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qilgan')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications_assigned_by_me', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlagan')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The Katta Mutaxasis this application is for (REQ-ARIZA-007).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Tayinlangan xodim')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_applications', to=settings.AUTH_USER_MODEL, verbose_name='Inkor qilgan')),
                ('sender', models.ForeignKey(blank=True, help_text='The requester whose purchase application raised this one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_applications', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
                ('status', models.ForeignKey(blank=True, help_text='Nullable because DEC-017 lets an administrator delete every status, and a master data page must not stop the workflow.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='xarid.arizastatus', verbose_name='Status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='xarid.department', verbose_name='Bo`lim nomi')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ('-kelib_tushgan_sana', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xarid_raqami', models.CharField(max_length=32, unique=True, verbose_name='Ariza raqami')),
                ('shartnoma_nomi', models.CharField(help_text='What the purchase is for (REQ-ARIZA-015).', max_length=255, verbose_name='Shartnoma nomi')),
                ('muddat_talabi', models.DateField(blank=True, null=True, verbose_name='Muddat talabi')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('pdf', models.FileField(blank=True, help_text='PDF, eng ko`pi bilan 10 MB (DEC-019).', storage=xarid.attachments.attachment_storage, upload_to='arizalar/%Y/%m', validators=[xarid.attachments.validate_pdf], verbose_name='Ariza (PDF)')),
                ('asl_pdf', models.FileField(blank=True, help_text='The attachment exactly as it was uploaded. Blank until an approval stamps pdf; from then on it names the original file.', storage=xarid.attachments.attachment_storage, upload_to='arizalar/%Y/%m', verbose_name='Asl ilova (PDF)')),
                ('yaratilingan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('stage', models.CharField(choices=[('awaiting_head', 'Bo`lim boshlig`i tasdig`ini kutmoqda'), ('awaiting_direktor', 'Direktor tasdig`ini kutmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Inkor etilgan')], default='awaiting_head', max_length=24)),
                ('bolim_boshligi_sanasi', models.DateTimeField(blank=True, null=True, verbose_name='Bo`lim boshlig`i tasdiqlagan sana')),
                ('direktor_sanasi', models.DateTimeField(blank=True, null=True, verbose_name='Direktor tasdiqlagan sana')),
                ('inkor_izohi', models.TextField(blank=True, help_text='Why it was refused; compulsory at the moment of refusal.', verbose_name='Inkor izohi')),
                ('inkor_sanasi', models.DateTimeField(blank=True, null=True, verbose_name='Inkor qilingan sana')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications', to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan')),
                ('department', models.ForeignKey(help_text="Filled from the requester's own account (DEC-018).", on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications', to='xarid.department', verbose_name='Bo`lim nomi')),
                ('inkor_qilgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications_rejected', to=settings.AUTH_USER_MODEL, verbose_name='Inkor qilgan')),
                ('raised_application', models.OneToOneField(blank=True, help_text="The department's own application this became on approval.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raised_from', to='xarid.application', verbose_name='Yaratilgan ariza')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications', to='xarid.arizastatus', verbose_name='Xozirgi holati')),
                ('tasdiqlagan_bolim_boshligi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications_approved_as_head', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan bo`lim boshlig`i')),
                ('tasdiqlagan_direktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_applications_approved_as_direktor', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlagan direktor')),
            ],
            options={
                'verbose_name': 'Xarid arizasi',
                'verbose_name_plural': 'Xarid arizalari',
                'ordering': ('-yaratilingan_sana', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Firma Nomi')),
                ('inn', models.CharField(blank=True, help_text='Nine digits. Optional: a foreign supplier has no Uzbek INN.', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='INN 9 ta raqamdan iborat bo`lishi kerak.')], verbose_name='Firma INN raqami')),
                ('daraja', models.CharField(blank=True, max_length=32, verbose_name='Daraja')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('inn', ''), _negated=True), fields=('inn',), name='unique_supplier_inn_when_given')],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_raqami', models.CharField(max_length=32, unique=True, verbose_name='Shartnoma raqami')),
                ('qiymati', models.DecimalField(decimal_places=2, help_text='In UZS (DEC-026); the total of the goods rows.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Shartnoma qiymati')),
                ('stage', models.CharField(choices=[('agreed', 'Kelishinlingan'), ('sent', 'Tasdiqlashga yuborilgan'), ('signed', 'Tuzilgan'), ('rejected', 'Inkor etilgan')], default='agreed', max_length=16)),
                ('inkor_izohi', models.TextField(blank=True, verbose_name='Izoh (Inkor etilgan)')),
                ('shartnoma_sanasi', models.DateField(blank=True, help_text='The date on the contract itself.', null=True, verbose_name='Shartnoma sanasi')),
                ('tolash_muddati', models.DateField(blank=True, null=True, verbose_name='To`lash muddati')),
                ('muddat_talabi', models.DateField(blank=True, null=True, verbose_name='Muddat talabi')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('yaratilingan_sana', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilingan sana')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='xarid.application', verbose_name='Ariza')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim shartnoma qilgan')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='xarid.shartnomastatus', verbose_name='Holati')),
                ('shartnoma_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='xarid.shartnomaturi', verbose_name='Shartnoma turi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='xarid.supplier', verbose_name='Firma nomi')),
            ],
            options={
                'verbose_name': 'Shartnoma',
                'verbose_name_plural': 'Shartnomalar',
                'ordering': ('-yaratilingan_sana', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('may_edit_contracts', models.BooleanField(default=False, help_text='At most one user holds this at a time (DEC-021). Granting it to somebody takes it from whoever had it.', verbose_name='Tahrirlash ruxsati')),
                ('department', models.ForeignKey(blank=True, help_text='DEC-018: the Xarid Arizasi form fills the department in from whoever is signed in. Nullable so accounts created before departments existed still save.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='xarid.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('user_type', models.ForeignKey(blank=True, help_text='A user with no type can open nothing that a role protects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='xarid.usertype')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_nomi', models.CharField(max_length=255, verbose_name='Buyurtma nomi')),
                ('buyurtma_soni', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Buyurtma soni')),
                ('olchov_birligi', models.CharField(help_text='ta, kg, m and so on. Free text (REQ-ARIZA-003).', max_length=16, verbose_name='O`lchov birligi')),
                ('part_number', models.CharField(blank=True, help_text="The supplier's own code for this item. Optional.", max_length=64, verbose_name='Part Number')),
                ('narxi', models.DecimalField(decimal_places=2, help_text='The price of one, in UZS (DEC-026).', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Narxi')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='xarid.contract', verbose_name='Shartnoma')),
            ],
            options={
                'verbose_name': 'Shartnoma qatori',
                'verbose_name_plural': 'Shartnoma qatorlari',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('buyurtma_soni__gte', Decimal('0.001'))), name='contract_line_quantity_is_positive', violation_error_message='Miqdori noldan katta bo`lishi kerak.'), models.CheckConstraint(condition=models.Q(('narxi__gte', Decimal('0.01'))), name='contract_line_price_is_positive', violation_error_message='Narxi noldan katta bo`lishi kerak.')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_nomi', models.CharField(max_length=255, verbose_name='Buyurtma nomi')),
                ('buyurtma_soni', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Buyurtma soni')),
                ('olchov_birligi', models.CharField(help_text='ta, kg, m and so on. Free text (REQ-ARIZA-003).', max_length=16, verbose_name='O`lchov birligi')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='xarid.application', verbose_name='Ariza')),
                ('mahsulot_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_items', to='xarid.mahsulotturi', verbose_name='Mahsulot Turi')),
            ],
            options={
                'verbose_name': 'Ariza qatori',
                'verbose_name_plural': 'Ariza qatorlari',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('buyurtma_soni__gte', Decimal('0.001'))), name='order_line_quantity_is_positive', violation_error_message='Buyurtma soni noldan katta bo`lishi kerak.')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('specialist_accepted', 'Xodim arizani qabul qildi'), ('purchase_rejected', 'Xarid arizasi inkor etildi')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='xarid.application', verbose_name='Ariza')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kimga')),
                ('purchase_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='xarid.purchaseapplication', verbose_name='Xarid arizasi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('application__isnull', False), ('purchase_application__isnull', True)), models.Q(('application__isnull', True), ('purchase_application__isnull', False)), _connector='OR'), name='notification_is_about_one_record', violation_error_message='A notification is about an application or a purchase application, not both and not neither.')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_nomi', models.CharField(max_length=255, verbose_name='Buyurtma nomi')),
                ('buyurtma_soni', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Buyurtma soni')),
                ('olchov_birligi', models.CharField(help_text='ta, kg, m and so on. Free text (REQ-ARIZA-003).', max_length=16, verbose_name='O`lchov birligi')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='xarid.purchaseapplication', verbose_name='Xarid arizasi')),
                ('mahsulot_turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_application_items', to='xarid.mahsulotturi', verbose_name='Mahsulot Turi')),
            ],
            options={
                'verbose_name': 'Xarid arizasi qatori',
                'verbose_name_plural': 'Xarid arizasi qatorlari',
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('buyurtma_soni__gte', Decimal('0.001'))), name='purchase_order_line_quantity_is_positive', violation_error_message='Buyurtma soni noldan katta bo`lishi kerak.')],
            },
        ),
    ]
