# Generated by Django 5.1.1 on 2026-09-18 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0003_contract_status_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='yuborgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim yuborgan'),
        ),
        migrations.AddField(
            model_name='contract',
            name='yuborilgan_sana',
            field=models.DateTimeField(blank=True, help_text='When this contract was last sent for approval. A resend overwrites it rather than keeping one row per attempt: DEC-024 makes a resend the same act again.', null=True, verbose_name='Tasdiqlashga yuborilgan sana'),
        ),
        migrations.AddField(
            model_name='contract',
            name='yuborishlar_soni',
            field=models.PositiveIntegerField(default=0, help_text='How many times this contract has gone for approval. The two columns above hold the last send and are overwritten by a resend, and the log TASK-UZK-052 builds cannot recover what was never recorded - a contract rejected and resent three times before that task ships would show one send and no sign of the other two. How many times it came back is the question the department will actually ask, and a count answers it without building that log early.', verbose_name='Necha marta yuborilgan'),
        ),
    ]
