# Generated by Django 5.1.1 on 2026-09-18 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0004_contract_sending'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='inkor_qilgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim inkor qilgan'),
        ),
        migrations.AddField(
            model_name='contract',
            name='inkor_sanasi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inkor qilingan sana'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tasdiqlagan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim tasdiqlagan'),
        ),
        migrations.AddField(
            model_name='contract',
            name='tasdiqlangan_sana',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan sana'),
        ),
    ]
