# Generated by Django 5.1.1 on 2026-09-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0006_shartnoma_status_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='invoice_sanasi',
            field=models.DateField(blank=True, help_text="The date on the supplier's invoice. Added by DEC-025 so that the Invoice stage of the dashboard's processing time has a source; the document names the stage but models no invoice anywhere.", null=True, verbose_name='Invoice sanasi'),
        ),
    ]
