# Generated by Django 5.1.1 on 2026-09-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0007_contract_invoice_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(help_text='What kind of record it was, such as Firma or Shartnoma.', max_length=64, verbose_name='Forma nomi')),
                ('record_label', models.CharField(help_text='What the record printed as when this happened.', max_length=255, verbose_name='Yozuv')),
                ('record_type', models.CharField(help_text="The model's label, such as xarid.supplier, for matching an approval to the creation it completes.", max_length=64)),
                ('record_id', models.PositiveIntegerField(help_text="The record's primary key, as a number rather than a foreign key: an entry about a deleted record must outlive it.")),
                ('action', models.CharField(choices=[('created', 'Created'), ('edited', 'Edited'), ('deleted', 'Deleted')], max_length=16, verbose_name='Amal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana/Soat')),
                ('approval_comment', models.TextField(blank=True, verbose_name='Tasdiq comment')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiq sanasi/vaqti')),
                ('approval_outcome', models.CharField(blank=True, help_text='Whether the decision approved the record or refused it.', max_length=16, verbose_name='Tasdiq natijasi')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('actor_department', models.ForeignKey(blank=True, help_text='The department the actor was in at the time. Recorded rather than read back from the account, so moving somebody between departments does not rewrite what the log says they did.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='xarid.department', verbose_name='Foydalanuvchi bo`limi')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Tasdiqlovchi foydalanuvchi')),
                ('approver_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_audit_entries', to='xarid.department', verbose_name='Tasdiqlovchi bo`lim')),
            ],
            options={
                'verbose_name': 'Log yozuvi',
                'verbose_name_plural': 'Log yozuvlari',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['record_type', 'record_id'], name='xarid_audit_record__0b476f_idx')],
            },
        ),
    ]
