# Generated by Django 5.1.1 on 2026-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0008_audit_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='izoh',
            field=models.TextField(blank=True, help_text='The comment the decision carried, kept here rather than read back from the record: what the sender was told is what the decision said at the time.', verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('specialist_accepted', 'Xodim arizani qabul qildi'), ('purchase_rejected', 'Xarid arizasi inkor etildi'), ('application_accepted', 'Arizangiz qabul qilindi'), ('application_rejected', 'Arizangiz inkor etildi')], max_length=32),
        ),
    ]
