# Generated by Django 5.1.1 on 2026-09-19 02:37

import xarid.attachments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0009_notification_sender_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pdf',
            field=models.FileField(blank=True, help_text='PDF, eng ko`pi bilan 10 MB (DEC-019).', storage=xarid.attachments.attachment_storage, upload_to='shartnomalar/%Y/%m', validators=[xarid.attachments.validate_pdf], verbose_name='Shartnoma (PDF)'),
        ),
    ]
