# Generated by Django 5.1.1 on 2026-09-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0011_contract_status_signed_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_purchasing',
            field=models.BooleanField(default=False, help_text='The department that works the approved requests: its Bo`lim Boshlig`i and Menejer are who Kelib Tushgan Arizalar is for. One department at a time, set here rather than matched on a name that anybody may rename.', verbose_name='Xarid bo`limi'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_purchasing', True)), fields=('is_purchasing',), name='only_one_purchasing_department', violation_error_message='Xarid bo`limi bitta bo`lishi kerak.'),
        ),
    ]
