# Generated by Django 5.1.1 on 2026-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0012_department_is_purchasing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='izoh',
            field=models.TextField(blank=True, help_text='The line of detail under the heading: the comment a decision carried, or what the notification is about. Kept here rather than read back from the record, so what somebody was told is what it said at the time.', verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('specialist_accepted', 'Xodim arizani qabul qildi'), ('purchase_rejected', 'Xarid arizangiz inkor etildi'), ('application_accepted', 'Arizangiz qabul qilindi'), ('application_rejected', 'Arizangiz inkor etildi'), ('purchase_awaiting_you', 'Yangi xarid arizasi tasdig`ingizni kutmoqda'), ('purchase_arrived', 'Tasdiqlangan xarid arizasi xarid bo`limiga keldi'), ('purchase_approved_by_head', 'Xarid arizangiz bo`lim boshlig`i tomonidan tasdiqlandi'), ('purchase_approved', 'Xarid arizangiz tasdiqlandi')], max_length=32),
        ),
    ]
