# Generated by Django 5.1.1 on 2026-09-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0014_application_status_follows_contract_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('specialist_accepted', 'Xodim arizani qabul qildi'), ('purchase_rejected', 'Xarid arizangiz inkor etildi'), ('application_accepted', 'Arizangiz qabul qilindi'), ('application_rejected', 'Arizangiz inkor etildi'), ('purchase_awaiting_you', 'Yangi xarid arizasi tasdig`ingizni kutmoqda'), ('purchase_arrived', 'Tasdiqlangan xarid arizasi xarid bo`limiga keldi'), ('purchase_approved_by_head', 'Xarid arizangiz bo`lim boshlig`i tomonidan tasdiqlandi'), ('purchase_approved', 'Xarid arizangiz tasdiqlandi'), ('contract_sent', 'Shartnoma tasdiqlashga yuborildi'), ('contract_status_changed', 'Shartnoma holati o`zgartirildi')], max_length=32),
        ),
    ]
