# Generated by Django 5.1.1 on 2026-09-20 18:22

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0015_alter_notification_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ('-yaratilingan_sana', '-id'), 'verbose_name': 'Shartnoma', 'verbose_name_plural': 'Shartnomalar'},
        ),
        migrations.AlterModelManagers(
            name='contract',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When this contract was deleted. Null for a contract in use. Deleting never removes the row (TASK-UZK-064): an Admin restores it from O`chirilgan Shartnomalar, and a contract number that was issued is not issued twice.', null=True, verbose_name='O`chirilgan sana'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Kim o`chirgan'),
        ),
    ]
