# Generated by Django 5.1.1 on 2026-09-20 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xarid', '0016_alter_contract_options_alter_contract_managers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('specialist_accepted', 'Xodim arizani qabul qildi'), ('purchase_rejected', 'Xarid arizangiz inkor etildi'), ('application_accepted', 'Arizangiz qabul qilindi'), ('application_rejected', 'Arizangiz inkor etildi'), ('purchase_awaiting_you', 'Yangi xarid arizasi tasdig`ingizni kutmoqda'), ('purchase_arrived', 'Tasdiqlangan xarid arizasi xarid bo`limiga keldi'), ('purchase_approved_by_head', 'Xarid arizangiz bo`lim boshlig`i tomonidan tasdiqlandi'), ('purchase_approved', 'Xarid arizangiz tasdiqlandi'), ('contract_sent', 'Shartnoma tasdiqlashga yuborildi'), ('contract_status_changed', 'Shartnoma holati o`zgartirildi'), ('contract_commented', 'Shartnoma bo`yicha yangi izoh')], max_length=32),
        ),
        migrations.CreateModel(
            name='ContractComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yozilgan sana')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_comments', to=settings.AUTH_USER_MODEL, verbose_name='Kim yozgan')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='xarid.contract', verbose_name='Shartnoma')),
            ],
            options={
                'verbose_name': 'Shartnoma izohi',
                'verbose_name_plural': 'Shartnoma izohlari',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
