# Generated by Django 5.1.1 on 2026-09-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArizaStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Status Nomi')),
                ('badge_colour', models.CharField(choices=[('orange', 'orange'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('gray', 'gray')], default='orange', max_length=16, verbose_name='Badge Rangi')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ariza Status',
                'verbose_name_plural': 'Ariza Statuslari',
                'ordering': ('name',),
            },
        ),
    ]
