# Generated by Django 5.1.1 on 2026-09-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_seed_shartnoma_statuses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arizastatus',
            options={'ordering': ('position', 'name'), 'verbose_name': 'Ariza Status', 'verbose_name_plural': 'Ariza Statuslari'},
        ),
        migrations.AlterModelOptions(
            name='shartnomastatus',
            options={'ordering': ('position', 'name'), 'verbose_name': 'Shartnoma Status', 'verbose_name_plural': 'Shartnoma Statuslari'},
        ),
        migrations.AddField(
            model_name='arizastatus',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Ro'yhatdagi va hisobot ustunlaridagi tartib. Bo'sh qoldirilsa, oxiriga qo'shiladi.", verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='shartnomastatus',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, help_text="Ro'yhatdagi va hisobot ustunlaridagi tartib. Bo'sh qoldirilsa, oxiriga qo'shiladi.", verbose_name='Tartib'),
        ),
    ]
