# Generated by Django 5.1.1 on 2026-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_place_seeded_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahsulotTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(help_text='Six digits, and the code the department knows the category by (DEC-023).', unique=True, verbose_name='Category Raqami')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Category Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulot Turi',
                'verbose_name_plural': 'Mahsulot Turlari',
                'ordering': ('category_number',),
            },
        ),
    ]
