# Generated by Django 5.1.1 on 2026-09-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_mahsulotturi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShartnomaTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Shartnoma Turi')),
            ],
            options={
                'verbose_name': 'Shartnoma Turi',
                'verbose_name_plural': 'Shartnoma Turlari',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='arizastatus',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Status Nomi'),
        ),
        migrations.AlterField(
            model_name='shartnomastatus',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Status Nomi'),
        ),
    ]
