# Generated by Django 5.1.1 on 2026-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_seed_shartnoma_turlari'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Bo`lim Nomi')),
            ],
            options={
                'verbose_name': 'Bo`lim',
                'verbose_name_plural': 'Bo`limlar',
                'ordering': ('name',),
            },
        ),
    ]
