# Generated by Django 5.1.1 on 2026-09-16 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Firma Nomi')),
                ('inn', models.CharField(blank=True, help_text='Nine digits, as the supplied contract form asks for. Optional: a foreign supplier has no Uzbek INN.', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', message='INN 9 ta raqamdan iborat bo`lishi kerak.')], verbose_name='Firma INN raqami')),
                ('daraja', models.CharField(blank=True, help_text='DEC-025 adds this because the dashboard filters by it, and does not say what values it takes. Free text until the customer says.', max_length=32, verbose_name='Daraja')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('inn', ''), _negated=True), fields=('inn',), name='unique_supplier_inn_when_given')],
            },
        ),
    ]
