# Generated by Django 5.1.1 on 2026-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizastatus',
            name='code',
            field=models.CharField(blank=True, choices=[('new', 'Yangi'), ('accepted', 'Qabul qilingan'), ('assigned', 'Tayinlangan'), ('cancelled', 'Bekor qilingan')], help_text='How the workflow finds this row. Set on the seeded statuses and empty on any an administrator adds. A renamed row keeps its code, which is the point.', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='arizastatus',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_ariza_status_code'),
        ),
    ]
