# Generated by Django 5.1.1 on 2026-09-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_department_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='may_edit_contracts',
            field=models.BooleanField(default=False, help_text='At most one user holds this at a time (DEC-021). Granting it to somebody takes it from whoever had it.', verbose_name='Tahrirlash ruxsati'),
        ),
    ]
