# Generated by Django 5.1.1 on 2026-09-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_may_edit_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Specialty Nomi')),
                ('category_number', models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Specialty',
                'verbose_name_plural': 'User Specialties',
                'ordering': ('name',),
            },
        ),
    ]
