# Generated by Django 5.1.1 on 2026-09-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userspecialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='badge_colour',
            field=models.CharField(choices=[('orange', 'orange'), ('blue', 'blue'), ('green', 'green'), ('yellow', 'yellow'), ('gray', 'gray')], default='orange', max_length=16, verbose_name='Badge Rangi'),
        ),
    ]
