# Generated by Django 5.1.1 on 2026-09-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mark_system_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='category_number',
            field=models.PositiveIntegerField(blank=True, help_text='Six digits when present (DEC-023).', null=True, verbose_name='Category Number'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='User Type'),
        ),
    ]
