# Generated by Django 5.1.1 on 2026-09-16 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usertype_category_number_alter_usertype_name'),
        ('reference', '0010_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='DEC-018: every user belongs to a department, and the Xarid Arizasi form fills it in from whoever is signed in. Nullable so that the users who existed before departments did still save; whether the Users page should insist on one is a question for the customer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='reference.department'),
        ),
    ]
