-- Database schema
--
-- Generated from the models by `python manage.py delivery_docs`. Do not edit
-- by hand: `python manage.py delivery_docs --check` fails when this file and
-- the code disagree, and the test suite runs that check.
--
-- SQLite DDL (DEC-040). This describes the schema the migrations produce; it
-- is not a script for another database or another server.

CREATE TABLE "xarid_application" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ariza_raqami" varchar(32) NOT NULL UNIQUE, "department_id" bigint NOT NULL REFERENCES "xarid_department" ("id") DEFERRABLE INITIALLY DEFERRED, "buyurtmachi_ismi" varchar(255) NOT NULL, "izoh" text NOT NULL, "pdf" varchar(100) NOT NULL, "sender_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "status_id" bigint NULL REFERENCES "xarid_arizastatus" ("id") DEFERRABLE INITIALLY DEFERRED, "kelib_tushgan_sana" datetime NOT NULL, "qabul_qilingan_sana" datetime NULL, "accepted_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "inkor_izohi" text NOT NULL, "inkor_qilingan_sana" datetime NULL, "rejected_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "assigned_to_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "xodim_qabul_qilgan_sana" datetime NULL, "tayinlangan_sana" datetime NULL, "assigned_by_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "stage" varchar(16) NOT NULL);
CREATE TABLE "xarid_applicationitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "buyurtma_nomi" varchar(255) NOT NULL, "buyurtma_soni" decimal NOT NULL, "olchov_birligi" varchar(16) NOT NULL, "application_id" bigint NOT NULL REFERENCES "xarid_application" ("id") DEFERRABLE INITIALLY DEFERRED, "mahsulot_turi_id" bigint NOT NULL REFERENCES "xarid_mahsulotturi" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "order_line_quantity_is_positive" CHECK ("buyurtma_soni" >= '0.001'));
CREATE TABLE "xarid_arizastatus" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_number" integer unsigned NULL CHECK ("category_number" >= 0), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "badge_colour" varchar(16) NOT NULL, "position" integer unsigned NOT NULL CHECK ("position" >= 0), "name" varchar(128) NOT NULL UNIQUE, "code" varchar(16) NOT NULL);
CREATE TABLE "xarid_auditentry" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "actor_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "actor_department_id" bigint NULL REFERENCES "xarid_department" ("id") DEFERRABLE INITIALLY DEFERRED, "form_name" varchar(64) NOT NULL, "record_label" varchar(255) NOT NULL, "record_type" varchar(64) NOT NULL, "record_id" integer unsigned NOT NULL CHECK ("record_id" >= 0), "action" varchar(16) NOT NULL, "created_at" datetime NOT NULL, "approver_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "approver_department_id" bigint NULL REFERENCES "xarid_department" ("id") DEFERRABLE INITIALLY DEFERRED, "approval_comment" text NOT NULL, "approved_at" datetime NULL, "approval_outcome" varchar(16) NOT NULL);
CREATE TABLE "xarid_contract" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "shartnoma_raqami" varchar(32) NOT NULL UNIQUE, "application_id" bigint NOT NULL REFERENCES "xarid_application" ("id") DEFERRABLE INITIALLY DEFERRED, "supplier_id" bigint NOT NULL REFERENCES "xarid_supplier" ("id") DEFERRABLE INITIALLY DEFERRED, "shartnoma_turi_id" bigint NULL REFERENCES "xarid_shartnomaturi" ("id") DEFERRABLE INITIALLY DEFERRED, "qiymati" decimal NOT NULL, "status_id" bigint NULL REFERENCES "xarid_shartnomastatus" ("id") DEFERRABLE INITIALLY DEFERRED, "stage" varchar(16) NOT NULL, "inkor_izohi" text NOT NULL, "yuborilgan_sana" datetime NULL, "yuborgan_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "tasdiqlagan_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "tasdiqlangan_sana" datetime NULL, "inkor_qilgan_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "inkor_sanasi" datetime NULL, "yuborishlar_soni" integer unsigned NOT NULL CHECK ("yuborishlar_soni" >= 0), "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "shartnoma_sanasi" date NULL, "tolash_muddati" date NULL, "invoice_sanasi" date NULL, "muddat_talabi" date NULL, "izoh" text NOT NULL, "pdf" varchar(100) NOT NULL, "yaratilingan_sana" datetime NOT NULL);
CREATE TABLE "xarid_contractitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "buyurtma_nomi" varchar(255) NOT NULL, "buyurtma_soni" decimal NOT NULL, "olchov_birligi" varchar(16) NOT NULL, "contract_id" bigint NOT NULL REFERENCES "xarid_contract" ("id") DEFERRABLE INITIALLY DEFERRED, "part_number" varchar(64) NOT NULL, "narxi" decimal NOT NULL, CONSTRAINT "contract_line_quantity_is_positive" CHECK ("buyurtma_soni" >= '0.001'), CONSTRAINT "contract_line_price_is_positive" CHECK ("narxi" >= '0.01'));
CREATE TABLE "xarid_contractstatuschange" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "contract_id" bigint NOT NULL REFERENCES "xarid_contract" ("id") DEFERRABLE INITIALLY DEFERRED, "from_status_id" bigint NULL REFERENCES "xarid_shartnomastatus" ("id") DEFERRABLE INITIALLY DEFERRED, "to_status_id" bigint NOT NULL REFERENCES "xarid_shartnomastatus" ("id") DEFERRABLE INITIALLY DEFERRED, "changed_by_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "changed_at" datetime NOT NULL);
CREATE TABLE "xarid_department" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_number" integer unsigned NULL CHECK ("category_number" >= 0), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "name" varchar(128) NOT NULL UNIQUE);
CREATE TABLE "xarid_mahsulotturi" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "category_number" integer unsigned NOT NULL UNIQUE CHECK ("category_number" >= 0), "name" varchar(128) NOT NULL UNIQUE, "description" text NOT NULL);
CREATE TABLE "xarid_notification" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "recipient_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "application_id" bigint NULL REFERENCES "xarid_application" ("id") DEFERRABLE INITIALLY DEFERRED, "purchase_application_id" bigint NULL REFERENCES "xarid_purchaseapplication" ("id") DEFERRABLE INITIALLY DEFERRED, "kind" varchar(32) NOT NULL, "izoh" text NOT NULL, "created_at" datetime NOT NULL, "read_at" datetime NULL, CONSTRAINT "notification_is_about_one_record" CHECK ((("application_id" IS NOT NULL AND "purchase_application_id" IS NULL) OR ("application_id" IS NULL AND "purchase_application_id" IS NOT NULL))));
CREATE TABLE "xarid_purchaseapplication" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "xarid_raqami" varchar(32) NOT NULL UNIQUE, "shartnoma_nomi" varchar(255) NOT NULL, "department_id" bigint NOT NULL REFERENCES "xarid_department" ("id") DEFERRABLE INITIALLY DEFERRED, "muddat_talabi" date NULL, "izoh" text NOT NULL, "pdf" varchar(100) NOT NULL, "asl_pdf" varchar(100) NOT NULL, "status_id" bigint NULL REFERENCES "xarid_arizastatus" ("id") DEFERRABLE INITIALLY DEFERRED, "created_by_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "yaratilingan_sana" datetime NOT NULL, "stage" varchar(24) NOT NULL, "tasdiqlagan_bolim_boshligi_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "bolim_boshligi_sanasi" datetime NULL, "tasdiqlagan_direktor_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "direktor_sanasi" datetime NULL, "inkor_izohi" text NOT NULL, "inkor_qilgan_id" integer NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "inkor_sanasi" datetime NULL, "raised_application_id" bigint NULL UNIQUE REFERENCES "xarid_application" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "xarid_purchaseapplicationitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "buyurtma_nomi" varchar(255) NOT NULL, "buyurtma_soni" decimal NOT NULL, "olchov_birligi" varchar(16) NOT NULL, "application_id" bigint NOT NULL REFERENCES "xarid_purchaseapplication" ("id") DEFERRABLE INITIALLY DEFERRED, "mahsulot_turi_id" bigint NOT NULL REFERENCES "xarid_mahsulotturi" ("id") DEFERRABLE INITIALLY DEFERRED, CONSTRAINT "purchase_order_line_quantity_is_positive" CHECK ("buyurtma_soni" >= '0.001'));
CREATE TABLE "xarid_shartnomastatus" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_number" integer unsigned NULL CHECK ("category_number" >= 0), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "badge_colour" varchar(16) NOT NULL, "position" integer unsigned NOT NULL CHECK ("position" >= 0), "name" varchar(128) NOT NULL UNIQUE, "is_completed" bool NOT NULL, "is_signed" bool NOT NULL);
CREATE TABLE "xarid_shartnomaturi" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_number" integer unsigned NULL CHECK ("category_number" >= 0), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "name" varchar(128) NOT NULL UNIQUE);
CREATE TABLE "xarid_supplier" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_number" integer unsigned NULL CHECK ("category_number" >= 0), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "name" varchar(128) NOT NULL UNIQUE, "inn" varchar(9) NOT NULL, "daraja" varchar(32) NOT NULL);
CREATE TABLE "xarid_userprofile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "user_type_id" bigint NULL REFERENCES "xarid_usertype" ("id") DEFERRABLE INITIALLY DEFERRED, "department_id" bigint NULL REFERENCES "xarid_department" ("id") DEFERRABLE INITIALLY DEFERRED, "phone_number" varchar(32) NOT NULL, "may_edit_contracts" bool NOT NULL);
CREATE TABLE "xarid_userspecialty" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_number" integer unsigned NULL CHECK ("category_number" >= 0), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "name" varchar(128) NOT NULL UNIQUE);
CREATE TABLE "xarid_usertype" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category_number" integer unsigned NULL CHECK ("category_number" >= 0), "is_active" bool NOT NULL, "created_at" datetime NOT NULL, "name" varchar(128) NOT NULL UNIQUE, "badge_colour" varchar(16) NOT NULL, "is_system_role" bool NOT NULL);
CREATE INDEX "xarid_application_department_id_3effc880" ON "xarid_application" ("department_id");
CREATE INDEX "xarid_application_sender_id_6b922c0e" ON "xarid_application" ("sender_id");
CREATE INDEX "xarid_application_status_id_2cca0a63" ON "xarid_application" ("status_id");
CREATE INDEX "xarid_application_accepted_by_id_b099be36" ON "xarid_application" ("accepted_by_id");
CREATE INDEX "xarid_application_rejected_by_id_1ff6c821" ON "xarid_application" ("rejected_by_id");
CREATE INDEX "xarid_application_assigned_to_id_d285e302" ON "xarid_application" ("assigned_to_id");
CREATE INDEX "xarid_application_assigned_by_id_dce2ecf2" ON "xarid_application" ("assigned_by_id");
CREATE INDEX "xarid_applicationitem_application_id_1eb316fd" ON "xarid_applicationitem" ("application_id");
CREATE INDEX "xarid_applicationitem_mahsulot_turi_id_186578af" ON "xarid_applicationitem" ("mahsulot_turi_id");
CREATE UNIQUE INDEX "unique_ariza_status_code" ON "xarid_arizastatus" ("code") WHERE NOT ("code" = '');
CREATE INDEX "xarid_auditentry_actor_id_2fccca2a" ON "xarid_auditentry" ("actor_id");
CREATE INDEX "xarid_auditentry_actor_department_id_68e43646" ON "xarid_auditentry" ("actor_department_id");
CREATE INDEX "xarid_auditentry_approver_id_a2db451d" ON "xarid_auditentry" ("approver_id");
CREATE INDEX "xarid_auditentry_approver_department_id_48563d39" ON "xarid_auditentry" ("approver_department_id");
CREATE INDEX "xarid_audit_record__0b476f_idx" ON "xarid_auditentry" ("record_type", "record_id");
CREATE INDEX "xarid_contract_application_id_43a769b5" ON "xarid_contract" ("application_id");
CREATE INDEX "xarid_contract_supplier_id_e32e8f01" ON "xarid_contract" ("supplier_id");
CREATE INDEX "xarid_contract_shartnoma_turi_id_e4052312" ON "xarid_contract" ("shartnoma_turi_id");
CREATE INDEX "xarid_contract_status_id_2b190295" ON "xarid_contract" ("status_id");
CREATE INDEX "xarid_contract_yuborgan_id_74a5e981" ON "xarid_contract" ("yuborgan_id");
CREATE INDEX "xarid_contract_tasdiqlagan_id_7b3aab29" ON "xarid_contract" ("tasdiqlagan_id");
CREATE INDEX "xarid_contract_inkor_qilgan_id_25e2f6d3" ON "xarid_contract" ("inkor_qilgan_id");
CREATE INDEX "xarid_contract_created_by_id_13d0b928" ON "xarid_contract" ("created_by_id");
CREATE INDEX "xarid_contractitem_contract_id_244ec20d" ON "xarid_contractitem" ("contract_id");
CREATE INDEX "xarid_contractstatuschange_contract_id_3929e921" ON "xarid_contractstatuschange" ("contract_id");
CREATE INDEX "xarid_contractstatuschange_from_status_id_73521203" ON "xarid_contractstatuschange" ("from_status_id");
CREATE INDEX "xarid_contractstatuschange_to_status_id_83533d81" ON "xarid_contractstatuschange" ("to_status_id");
CREATE INDEX "xarid_contractstatuschange_changed_by_id_2e2ea40c" ON "xarid_contractstatuschange" ("changed_by_id");
CREATE INDEX "xarid_notification_recipient_id_e222b6a9" ON "xarid_notification" ("recipient_id");
CREATE INDEX "xarid_notification_application_id_010b54e8" ON "xarid_notification" ("application_id");
CREATE INDEX "xarid_notification_purchase_application_id_b908e3f5" ON "xarid_notification" ("purchase_application_id");
CREATE INDEX "xarid_purchaseapplication_department_id_b5b58f1d" ON "xarid_purchaseapplication" ("department_id");
CREATE INDEX "xarid_purchaseapplication_status_id_96604a41" ON "xarid_purchaseapplication" ("status_id");
CREATE INDEX "xarid_purchaseapplication_created_by_id_fe0fc747" ON "xarid_purchaseapplication" ("created_by_id");
CREATE INDEX "xarid_purchaseapplication_tasdiqlagan_bolim_boshligi_id_6ba1836f" ON "xarid_purchaseapplication" ("tasdiqlagan_bolim_boshligi_id");
CREATE INDEX "xarid_purchaseapplication_tasdiqlagan_direktor_id_f4e06cab" ON "xarid_purchaseapplication" ("tasdiqlagan_direktor_id");
CREATE INDEX "xarid_purchaseapplication_inkor_qilgan_id_d91c75d9" ON "xarid_purchaseapplication" ("inkor_qilgan_id");
CREATE INDEX "xarid_purchaseapplicationitem_application_id_d2039a67" ON "xarid_purchaseapplicationitem" ("application_id");
CREATE INDEX "xarid_purchaseapplicationitem_mahsulot_turi_id_93fca779" ON "xarid_purchaseapplicationitem" ("mahsulot_turi_id");
CREATE UNIQUE INDEX "unique_supplier_inn_when_given" ON "xarid_supplier" ("inn") WHERE NOT ("inn" = '');
CREATE INDEX "xarid_userprofile_user_type_id_11f1b089" ON "xarid_userprofile" ("user_type_id");
CREATE INDEX "xarid_userprofile_department_id_127189bf" ON "xarid_userprofile" ("department_id");
